services:
  apigateway:
    image: apigateway
    build:
      context: .
      dockerfile: ApiGateway/Dockerfile

  genaiservice:
    image: genaiservice
    build:
      context: .
      dockerfile: GenAIService/Dockerfile

  grpcservice:
    image: grpcservice
    build:
      context: .
      dockerfile: GrpcService/Dockerfile

  notificationservice:
    image: notificationservice
    build:
      context: .
      dockerfile: NotificationService/Dockerfile

  paymentservice:
    image: paymentservice
    build:
      context: .
      dockerfile: PaymentService/Dockerfile

  restservice:
    image: restservice
    build:
      context: .
      dockerfile: RestService/Dockerfile

  soapservice:
    image: soapservice
    build:
      context: .
      dockerfile: SoapService/Dockerfile